- name: Deploy MongoDB and Spring Boot on Minikube
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Apply MongoDB Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: mongodb-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: mongodb
            template:
              metadata:
                labels:
                  app: mongodb
              spec:
                containers:
                - name: mongodb-container
                  image: mongo:latest
                  ports:
                  - containerPort: 27017
  
      

    - name: Apply MongoDB Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: mongodb-service
            namespace: default
          spec:
            selector:
              app: mongodb
            ports:
            - protocol: TCP
              port: 27017
            type: ClusterIP

    - name: Apply Spring Boot Deployment
      k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: spring-boot-deployment
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: spring-boot
            template:
              metadata:
                labels:
                  app: spring-boot
              spec:
                containers:
                - name: spring-mongo-container
                  image: haythemkaouech/spring-mongo:latest
                  ports:
                  - containerPort: 8080
   
      

    - name: Apply Spring Boot Service
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: spring-boot-service
            namespace: default
          spec:
            selector:
              app: spring-boot
            ports:
            - protocol: TCP
              port: 8080
              targetPort: 8080
            type: NodePort
